on:
  push:
    branches:
      - main
name: Deploy Application to Staging/Production

jobs:
  call-deploy-app-staging:
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: stg
    secrets: inherit
  call-deploy-app-production:
    uses: ./.github/workflows/deploy-app.yml
    needs: call-deploy-app-staging
    with:
      environment: prd
    secrets: inherit
