on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
name: Deploy Application

env:
  AZURE_FUNCTIONAPP_NAME: "your-app-name" # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: "6.0.x" # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: build-ui
        run: npm run build
        working-directory: ./src/ui

      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: build-api
        run: dotnet build --configuration Release
        working-directory: ./src/api

      - name: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        name: azure-environment-setup
        with:
          scope: subscription
          region: southcentralus
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./infrastructure/setup-subscription.bicep
          parameters: setup-subscription.parameters.${{ inputs.environment }}.json
          failOnStdErr: false

      - name: get-api-key
        uses: azure/cli@v1
        with:
          inlineScript: |
            key=az staticwebapp secrets list --name ${{ steps.azure-environment-setup.outputs.staticWebsiteName }} --query "properties.apiKey"
            echo "::add-mask::$key"
            echo "key=$key" >> "$GITHUB_OUTPUT"

      - uses: Azure/static-web-apps-deploy@v1
        name: deploy-static-site
        with:
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ steps.get-api-key.outputs.key }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src/ui/build/"
